introduction/introduce_yourself/zzyzy.txt
Added zzyzy.txt to introduce myself.
=> Added zzyzy

introduction/introduce_yourself/joel.txt
contribution for hacktoberfest 2k19
=> introducing myself

algorithms/52/lucas.c
Resolves Issue #52 
Added Lucas sequence recursive algortihm
Basic C program, compile with `gcc lucas.c`
=> Adding Lucas sequence recursive algorithm

introduction/introduce_yourself/ryan.txt
Resolves Issue #1
Please explain the changes you made in detail here.
Added an a text file in introduction that introduces myself.
=> Added ryan.txt

introduction/introduce_yourself/kunal.txt
resolves Issue #<50>
Added kunal.txt to introduce yourself folder.
=> Added kunal.txt

introduction/introduce_yourself/ayushman.txt
resolves Issue #1 
Wrote the details of Ayushman
=> Ayushman's Details

introduction/introduce_yourself/dharmick.txt
Issue #1 
my details are given in dharmick.txt
=> my details

introduction/introduce_yourself/Deepta.txt
esolves Issue #1
Added details of myself in the introduction folder.
=> Added details of Deepta

introduction/introduce_yourself/ashwin.txt
Resolves Issue #1
Added my details in the introduction folder
=> Added details of Ashwin

introduction/introduce_yourself/191CS104.txt
esolves Issue #1 
Added details of myself in the introduction folder.
=> Added Details of Aditya Kumar 

introduction/introduce_yourself/nityesh.txt/nityesh
esolves Issue #1 <issue_number>
Added details of myself in introduction folder.
=> Added details of Nityesh

introduction/introduce_yourself/rp7.txt, introduction/introduce_yourself/ryan.txt
issue#1
i  made  changes to two files rp7 and ryan.
=> added details of rakshit

development/Sockets/client.py, development/Sockets/server.py, development/TableSearch/index.html, development/TableSearch/table-search.js
Resolves Issue #30
Hello @kampaitees, here is the UDP chat program for review, if you please!  Thank you :)
Converted the python chat application from using the connection-based TCP protocol,  to use the no-guarantees based UDP protocol.
Step 1.  Navigate to the /development/Sockets directory and start the server in a new terminal or terminal tab using this command.
`python3 server.py`
Step 2. Then we will start the client.  Open a new terminal or terminal tab, navigate to the /development/Sockets directory, and enter:
`python3 client.py`
Step 3.  Success, you can now chat between the client and server over the UDP protocol!
=> Converted TCP Socket program to UDP

development/Sockets/client.py, development/Sockets/server.py, development/TableSearch/index.html, development/TableSearch/table-search.js
Resolves Issue #40 
Hi @harshnitk17 😃 , if you could please review, that would be great!  Thanks!
As requested, implemented a search for a plain HTML table which dynamically changes the table based on the searched input.
Simply open the index.html file with your favorite browser.
=> added html table with javascript dynamic searching

introduction/introduce_yourself/Aastha.txt
resolves Issue #1 
This pull request is my introduction.
=> Added Aastha.txt

introduction/introduce_yourself/prajwal.txt
issue number #1 
Introduced myself
=> added details of prajwal

introduction/introduce_yourself/arunava.txt
Resolves Issue #1
Added my details.
=> Added details of Arunava

introduction/introduce_yourself/keerti.txt
Added details of Keerti in introduction folder.
=> Added details of Keerti

introduction/introduce_yourself/Janmansh.txt
Added my Details in the Introduction folder.
=> Added my Introduction

introduction/introduce_yourself/s1.txt
resolves Issue #1
Added my details:Name
Branch
Year
Interest
=> details of hacktoberfest 2K19

introduction/introduce_yourself/myintro.txt
=> Details of myintro added

introduction/introduce_yourself/himanshu.txt
Added details of myself in the introduction fodfer
=> added details of himanshu

introduction/introduce_yourself/rakshita.txt
esolves Issue #1 
added details of myself
=> added new introduction details of Rakshita

introduction/introduce_yourself/saish.txt.txt
resolvesolves Issue #1 
I have added my details .
Please list all the steps required to run in details. Preferably specify steps for all platforms.
=> Added details of Saish

introduction/introduce_yourself/Navaneeth.txt
Added a new file indroducing myself
=> intro demo

introduction/introduce_yourself/mihir.txt.txt
=> Mihir's Intro

introduction/introduce_yourself/chandan.txt
esolves Issue #1 
added details of chandan kuamr
=> Add Chandan Introduction

systems/SQL Operations/smartphones.sql, systems/SQL Operations/smartphones_SQLite.sql
resolves Issue #23
This PR tries to resolve the issue #23 by making the folder 'SQL Operations' within 'systems' folder and adding a new SQLite script.
The sql file creates a table, insert some values into it and includes 3 queries as requested by the Issue.
in order to run the script, open the SQLite prompt and type:
`
sqlite> .read smartphones_SQLite.sql
`
=> SQL Operations using SQLite3

development/form validation/jsvalidation.html, systems/SQL Operations/MySQL.sql
This MR resolves Issue  #23 and #36 
1. MySQL Operations: I had to create a database and create a table within it with particular columns. While describing each column I also had to specify what kind of input MySQL should expect (VARCHAR(32) for 32 character long string, for ex). Then I inserted all entries mentioned in the issue in the database.
2. JS Validation: The validation is done with vanilla JS (no jQuery or Bootstrap validation). This was made possible with using regex strings corresponding to emails and phone numbers. 
#23 is made with MySQL. Find it under _systems/SQL Operations/MySQL.sql_.
#36 can be found under _development/form validation/jsvalidation.html.
=> #23 (MySQL Operations) and #36 (Javascript Validation)

introduction/introduce_yourself/sudiksha.txt
esolves Issue #<issue_number>
Please explain the changes you made in detail here.
Please list all the steps required to run in details. Preferably specify steps for all platforms.
dsvsddc
=> added details of medsad

introduction/introduce_yourself/Hello.txt, introduction/introduce_yourself/karthik.txt
esolves Issue #<issue_number>
Added personal details in the introduction folder
=> Personal details

introduction/introduce_yourself/NandaKishore.txt
Resolves Issue#1
##Description 
Added details myself in introduction folder
=> NandaKishore has been added

algorithms/44_generation_of_primes/generateprime.cpp
resolves Issue #44 
Added a program to generate prime numbers between low and high value.
Algorithm used is Segmented Sieve of Eratosthenes
1. Go to Algorithms/44_generation_of_primes/
2. Open the program and run it.
=> added Generate-prime problem using segmented sieve

algorithms/44_generation_of_primes/index.html, algorithms/44_generation_of_primes/index.js
Issue #44 
Just run index.html file and follow the instructions.
=> Prime exercise in JavaScript done.

algorithms/60-Insertion Sort/insertion_sort.py
resolves Issue #60 
The insertionsort-algorithm was implemented using python.
In order to not mutate the given input, the input-array is first copied prior to any sorting. 
This implementation of insertionsort was created using python 3.7.4 on a Windows machine.
The implementation defines a function `insertion_sort(unsorted_input)` which takes an unsorted array as a parameter.
An example call to this function:
```
a = [4,1,8,5,3,89,12]
print(insertion_sort(a))
```
=> implemented insertion sort in python

algorithms/60-Insertion Sort/insertion_sort.c
Solves Issue #60 
Implemented insertion sort using C.
Compiled with TDM_GCC 5.1.0 on Windows 10
Program contains a driver code inside main() function, which declares an array and calls the function to sort it. Run gcc insertion_sort.c to compile and then execute a.exe
=> Add insertion sort in C

algorithms/60-Insertion/insertion_sort.c
Resolves Issue #60 
i have created C++ program for insertion sort
=> Created file

algorithms/51/dec2bin.c, algorithms/52/dec2bin.c
esolves Issue #51 
I have added the code to convert decimal number into binary number using C language.
Preferred language is C
It needs gcc compiler to compile it.
If you are using windows.You can download gcc from here:- https://preshing.com/20141108/how-to-install-the-latest-gcc-on-windows/
To compile run the following commands:
cc <file.c>
To run the code:
./a.out.
=> Decimal to binary conversion

algorithms/56/k_largest.c
Resolves Issue #56 
- add `algorithms/56/k_largest.c`
- implement median-of-medians algorithm in it as a filter
- uses `long` datatype to handle large enough integers
- runs in `O(n)`
The easiest way is
```bash
3
10
25
21
98
100
76
22
43
60
89
87
43
```
/cc @NKH123 for review
=> k_largest: implement median of medians

introduction/introduce_yourself/Himanshu.txt
=> Created Introduction File

Issue 166 - IPv4 Class/C.c
Resolves Issue #166 
Added an IPv4 class identifier in C
Compile the C code.
The input and output format are exactly as mentioned in the Issue Statement.
=> add IPv4 class finder in C

.classpath, .gitignore, .project, algorithms/60-Insertion-Sort/InsertionSort.java
resolves Issue #91
Author : Rabinson Ghatani
Date: 2019/10/02
The Insertion Sort Algorithm is implemented in java. The output of the program sorts the array of number in ascending order.
IDE: Eclipse
JRE System library: java-8-openjdk-amd64
OS : Ubuntu
Compile and run InsertionSort.java file which is inside /algorithms/60-Insertion-Sort/
=> Insertion Sort in Java

algorithms/PasswordStrength/check.py
Issue #41
Hi @SkaMessi10. Could you review the code please? 
Thanks!
=> Pwdstrength

algorithms/51/dec2bin.cpp, algorithms/60-InsertionSort/insertion_sort.cpp, introduction/introduce_yourself/Adithya.txt
Resolves Issue #60 
Implemented Insertion Sort using C++ and the algorithm has been clearly commented upon.
=> Program to implement insertion sorting

algorithms/60-Insertion Sort/insertion_sort.cpp
Resolves Issue #60 
The insertionsort-algorithm was implemented using C++
In order to not mutate the given input, the input-array is first copied prior to any sorting.
This implementation of insertionsort was created using C++ on a Windows machine.
The implementation defines a function insertionSort(unsorted_input, number of array) which takes an unsorted array as a parameter.
An example call to this function:
int arr[] = { 12, 11, 13, 5, 6 };  
int n = sizeof(arr) / sizeof(arr[0]);  
insertionSort(arr, n);  
printArray(arr, n);
=> add issues 60-Insertion Sort

development/Login_page/css/style.css, development/Login_page/index.html, development/Login_page/js/login.js
Resolves Issue #132 
Please explain the changes you made in detail here.
I have made Login folder inside the development directory in which I use HTML for making form and CSS for styling and JAVASCRIPT for form validation. 
HTML
CSS
JAVASCRIPT
Please list all the steps required to run in details. Preferably specify steps for all platforms.
Just run the index .html file inside the Login_page
=> Responsive Login page using html,css and javascript

algorithms/12/Number_of_pairs.c
Resolves Issue #12
The algorithm is pretty simple, it requires 3 variables and one loop, the time complexity is O(n) and space complexity is O(1). 
A left and right cursor are initialized to the extremes elements of the array, then the loop is repeated until the 2 cursors overlap. In each iteration the elements in the array pointed by the cursor are summed, if the sum is equal to the target, the count of pairs is increased by 1 and the cursor are moved toward the center of the array. If the sum is above the target then the right cursor is moved to the left by 1 position, this is because the array is sorted so we are sure that by moving the right cursor to the left the sum at the next iteration will decrease. If the sum is below target the opposite operation is performed on the left …
=> Add Optimised Number of pairs #12

machineLearning/abalone_age/dtc/Abalone Age Prediction.ipynb
Here first I converted the .data file to python readable format using Numpy then checked whether null or nan values are there or not then did the preprocessing of categorical data. Then I applied the decision tree classifier for doing the classification task.
=>  added abalone_age_prediction.ipynb

algorithms/16/upper-case.c, algorithms/60-Insertion/insertion_sort.c
Resolves Issue #16 
Created a C program for conversion of Small letter to Capital letter
=> Upper case

algorithms/43/nCrDynProg.cpp
Resolves Issue #43 
Solved the DP question using C++
Compile the code using C++ compiler.
The program reads from STDIN until "-1 -1" is encountered and for each line, containing "n r", the value of nCr is printed out into STDOUT.
=> Solve nCr using DP

systems/StringTokenization/main.c
Resolves Issue #<22>
Removed the inbuilt functions used.
used 2d arrays as specified.
indented properly with comments
On any compiler Input according to instructions.
code compiles without errors or warnings , works properly for the new changes also
=> issue #22 final code

development/GameOfLife/simulate.py
Resolves Issue #47 
Converted the sample code from Brian's Brain to Conway's Game of Life
Updated the rule set and refactored variable names
=> Converted Brians Brain to Conway's Game of Life

algorithms/Recursion/base_conversion.c, algorithms/Recursion/code_refactoring.c
Resolves Issue #37 
- Reformat ```algorithms/Recursion/code_refactoring.c``` so the code adheres to good programming practices
- Add ```algorithms/Recursion/base_conversion.c``` to convert a decimal number to any base (2 <= base <= 16)
=> Refactor code and add base conversion

systems/Issue 166 - IPv4 Class/C#.cs
Resolves Issue #166 
Added an IPv4 class identifier in C#.
Compile the C# code.
@krithikvaidya Please review the PR.
=> Update Issue 166 - IPv4 class for C#

systems/info_script.sh
Resolves Issue #49
I have written a simple script for the requirements given.
I have made use of BASH to write my script on a Ubuntu OS
On a Ubuntu operating system:
1. Check for the permission of the script by doing: **ll script-name**
2. If it has executable permissions then go to step 4 else go to step 3.
3. We need to give executable permissions: **chmod +x script-name**
4. Type: **./ script-name**  or Type : **bash script-name**
- [YES] Code compiles correctly.
- [YES] Changes are tested properly.
- [YES] Followed the Contributing guidelines.
- [YES] Resolved merge conflicts, if any.
=> Update Issue #49

systems/193/vigenere.cpp
Resolves Issue #193 
Created a CPP program that encrypts/decrypts a text using vignere cipher.
The input can have alphanumeric characters and white spaces. It can also have punctuation and special characters. 
The Cipher will only operate on the alphabets though, i.e. [ a-z] and [A-Z].
**Sample Input:**
Enter the key used for encryption : 
fortification
Enter the text for encryption : 
defend the east wall of the castle
**Output:**
Encrypted Text : iswxvibjexiggbocewkbjeviggqs
Decrypted Text : defendtheeastwallofthecastle
Please review the code @Z0Marlin
=> Created a cpp program which encrypts/decrypts a text using vignere cipher

algorithms/72/maximum_subarray_sum.c
Resolves Issue #72 
- Created a new folder `algorithms/72`, and added a file `maximum_subarray_sum.c`
`cd algorithms/72`
`gcc maximum_subarray_sum.c`
`./a.out`
=> Added maximum_subarray_sum.c

introduction/introduce_yourself/Himanshu.txt
Resolves Issue #<issue_number>
Please explain the changes you made in detail here.
Please list all the steps required to run in details. Preferably specify steps for all platforms.
=> Revert "Created Introduction File"

machineLearning/33/Airfoil_Noise_prediction.ipynb
Here first I had converted the data to readable format then check whether there are null values than did feature scaling then split the data into 80-20 ratio and finally applied the linear regression model to calculate the mean and log mean squared error.
=> Added Airfoil_Noise_Prediction.ipynb file

systems/153/opengl_window_creation.cpp
Resolves Issue #153 
Added a source file for a program that creates an OpenGL context and an application window to render in using GLFW.
- Install GLFW
- Install GLAD
- Install OpenGL
- Compile source code with glad.c
- When compiling include GLFW and GLAD header files
- When compiling link GLFW and OpenGL libaries
- Some additional libraries that you might need to link when compiling with gcc on Linux:
**-lglfw3 -lGL -lX11 -lpthread -lXrandr -lXi -ldl**
=> Added OpenGL Window Creation

algorithms/#152
Resolves issue:#152
#createing 100000 random numbers
=> create random numbers

systems/150/single_byte_xor.py
Resolves Issue #150 
Created ```systems/150``` folder and added ```systems/150/single_byte_xor.py``` which contains an implementation of single-byte XOR cipher.
=> Add single-byte XOR cipher

Issue 166 - IPv4 Class/Ruby.rb
Resolves Issue #166 
I upload the solution in Ruby
Checklist
=> IPv4 Classes in Ruby

systems/Issue 166 - IPv4 Class/Golang.go
=> Placed Golang program inside system/Issue 166 - IPv4 Class

Issue 166 - IPv4 Class/Javascript.js
Resolves Issue #166 
Added an IPv4 class identifier in Javascript
node Javascript.js
=> Update Issue 166 - IPv4 class for JavaScript

systems/193/vigenere.py
Resolves Issue #193 
Simulates Vigenere Cipher for all capital, all small as well as mixed alphabetical plaintexts and keywords.
Accomplishes both encryption and decryption with the complexity of O(N)
Run 'python3 vigenere.py' on Unix console
- [.] Code compiles correctly.
- [.] Changes are tested properly.
- [.] Added the README / documentation, if necessary.
- [.] Followed the Contributing guidelines.
- [.] Resolved merge conflicts, if any.
=> Implementation of Vigenere Cipher using Python

algorithms/239/gcdeuclid.cpp
Resolves Issue #<239>
Its Been A day and i haven't been assigned to this yet.
I saved this code in algorithms directory with the folder name 239.
Please review the code .
Made use of Euclidian Algorithm as specified.
Works On Any Compiler. 
Input According To instructions.
=> Code for GCD of 2 Numbers

Issue 166 - IPv4 Class/Golang.go
Resolves Issue #166
Program to classify IP Address in Golang
Golang
1] Use online editor https://repl.it/languages/go (Replit) . Copy , Paste and just Run it
2] Download the Golang.go file and save it on Desktop. Use cmd :
a] Go to particular directory where file is stored. 
b] Use command : go build  (It will generate Golang.exe file)
c] Use command : Golang  (It will run Program)
=> Added IP Address Classification Program in Golang

algorithms/16/upper-case.cpp, algorithms/29/fexpo.cpp, algorithms/Random_Number_Generation_#152/Random_number1.txt, algorithms/Random_Number_Generation_#152/Random_number2.txt, algorithms/Swap_with_max/SWAP.cpp
Resolves Issue #16 
The code in which all the small-case letters are converted to upper-case while other characters remain same. Here i have replaced the ascii values of small-case letters by ascii values of upper-case letters.
=> Upper-case issue solved

development/form validation/bilalJsValidation.html
Resolves Issue #36 
made three functions called `validateForm` `validEmail` `validPhoneNumber`
`validEmail` method is used to check if an email is valid or not. If email is not valid it shows an alert with the message `invalid email formate`. I used regex for email validation. 
`validPhoneNumber` method is used to check if phone number is valid or not. If a phone number is not valid it shows an alert with the message `invalid phone number formate`. I used regex for phone number validation. 
`validateForm` in this method I made a valuable called `check` which value we update with return value from both above function. if formate is not valid we return `false` and this `false` saved in check variable which then passed to form.
copy this path of `BilalJsformValidation.html` which is located …
=> form validation

algorithms/python-to-cpp/py_to_cpp.cpp
Resolves Issue #260 
Converted code given in Python to CPP
=> code in cpp for the code given in python

algorithms/DFS/DFS.cpp
Resolves Issue #17 
In this I have made a folder of DFS inside algorithms and in this folder I have given my code using C++ and I used the iterative approach to wrote this code.
Language used:C++
> ### Issue requirements / progress
> * [x]  Read about Depth first search traversal for a graph.
> * [x]  Implement DFS using adjacency matrix.
> * [x]  Change above code to work with adjacency list.
Just go to program and run code in any GCC compiler.
=> DFS Graph Traversal using c++

development/diff/differences.js, development/diff/index.html
Resolves Issue #14 
missing and green for the words which are newly added.
1. Open the html file, `index.html`,  using your favorite browser.
2. Notice there are 3 paragraph boxes.  The top left or first paragraph box is the source of truth.  It is used to show the difference between its text and whatever is contained in the top right or second paragraph box.
3. Any text in the same position in both boxes will just display in the third box with out a background.  Any text in the first box that is not in the second, will display in the third box and will have a green background.  Any text in the second box that is not matched in the first box will display with a red background in the third box.
=> [Solved] "Get the difference between two text paragraphs(Ever used `git diff` !)"

algorithms/Issue_53/snake/test.js
Resolves Issue #53 
I iterate through the "snakeLength" and add all positions, except the head of the snake, to a new array.
Then i am able to search the  snakeArray for the hit at the body.
i hope this is enough :)
=> Added termination condition
